#!/bin/bash

gcc ./test.c -o test
./test ijk 5 500 10 > ijk.csv
./test jik 5 500 10 > jik.csv
./test ikj 5 500 10 > ikj.csv
./test kij 5 500 10 > kij.csv
./test jki 5 500 10 > jki.csv
./test kji 5 500 10 > kji.csv
